### PR TITLE
hello g

### PR DESCRIPTION
**Pull request by prakashNalla**

### CODE REVIEW

**Comment by T-Dynamos** [comment]
May i get info of update?

**Comment by T-Dynamos** [comment]
update `settings.py` file to resolve then i will merge

**Comment by prakashNalla** [comment]
hi g i remove not use import statement and try increase text look gud. thank u

**Comment by T-Dynamos** [comment]
Thanks g  for changes  . What about if i make you contributor?

**Comment by prakashNalla** [comment]
yes g i ll be very happy thank you

**Pull request merged**
